project:
  type: book

book:
  title: "statabook-example"
  author: "Norah Jones"
  date: today
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/chap1.qmd
    - chapters/summary.qmd
    - chapters/references.qmd

bibliography: references.bib

format:
  docx:
    theme: cosmo
    reference-doc: custom_reference.docx
    execute:
      echo: false
      message: false
      warning: false
    filters:
      - filters/landscape.lua
    



